### ISSUE TITLE
Incorrect rendering of valid (I think!) docstring

### ISSUE THREAD

**Issue by stefanv** [anntzer/speedoc#1]
To reproduce: `speedoc skimage.transform.rescale`

Look at the notes and examples sections:

```
              Notes

              Modes 'reflect' and 'symmetric' are similar, but differ in whether the edge pixels are duplicated during the reflection.  As an example, if an  array  has  values
              [0,  1, 2] and was padded to the right by four values using symmetric, the result would be [0, 1, 2, 2, 1, 0, 0], while for reflect it would be [0, 1, 2, 1, 0, 1,
              2].

              Examples.sp
              >>> from skimage import data
              >>> from skimage.transform import rescale
              >>> image = data.camera()
              >>> rescale(image, 0.1).shape
              (51, 51)
              >>> rescale(image, 0.5).shape
              (256, 256)
```

Notes is not rendered in bold, examples heading has formatting characters at the end.

**Comment by anntzer** [comment]
Looks like two bugs on sphinx's side: https://github.com/sphinx-doc/sphinx/issues/6331 (well, one bug -- the bad markup -- and one wishlist -- add highlighting to `.. rubric::`, which shouldn't be too hard as there's already highlighting for the similar `.. topic::`).

**Comment by anntzer** [comment]
The bad markup is fixed as of sphinx master (https://github.com/sphinx-doc/sphinx/pull/6343); the lack of highlighting could perhaps be reported as a separate issue to them but in any case I think there isn't anything else to be done on this side.
Thanks for the report.
